### ISSUE TITLE
Better instructions would be great

### ISSUE THREAD

**Issue by ikaun** [thelazyone/lazy-tree#1]
I see there is a Create Tree in Mesh but then what?

**Comment by thelazyone** [comment]
Very true! 
I was waiting to restructure the interface a little bit (creating sections and presets) before adding a visual guide, but it would help right now too! 

In any case, the plugin should be installed with the .py file, like this:
<img width="371" alt="image" src="https://github.com/thelazyone/lazy-tree/assets/10134358/37561bd2-994e-4846-b636-641f7dd8058c">

...and a new option in the "Create" side menu should appear:
<img width="238" alt="image" src="https://github.com/thelazyone/lazy-tree/assets/10134358/b029c850-1a3b-49ab-acf3-7e761e7b153b">

**Comment by thelazyone** [comment]
Closed in recent commit
