### ISSUE TITLE
Error when loading the add-on in Blender

### ISSUE THREAD

**Issue by pyttroll** [thelazyone/lazy-tree#5]
Hi,

I seems to have an issue when loading the add-on in Blender, here's the trace:

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.3/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/pyt/Library/Application Support/Blender/3.3/scripts/addons/lazy-tree.py", line 28, in <module>
    current_script_dir = bpy.context.space_data.text.filepath
AttributeError: '_RestrictContext' object has no attribute 'space_data'

```

Great job anyway, I'm looking forward to give it a try.

**Comment by thelazyone** [comment]
Looks like i didn't do proper testing before the last commits. 
I'll try to find a workable solution tomorrow! Sorry for the inconvenience!

**Comment by pyttroll** [comment]
No worries, thanks!

**Comment by thelazyone** [comment]
The latest commit should fix that. 
I am still juggling to find a code that can be used both as plugin and loaded directly in the blender text editor. RIght now the path-to-the-py-files is hardcoded, which is very sub-optimal. But it shouldn't fail.

**Comment by pyttroll** [comment]
Works like a charm, thanks!
