### ISSUE TITLE
Generated tree is not printable

### ISSUE THREAD

**Issue by ikaun** [thelazyone/lazy-tree#6]
The tree generate in Blender looks amazing but when added to Chitubox... it looks like this. It appears the sections are not complete?

![image](https://github.com/thelazyone/lazy-tree/assets/61319817/cfac4958-4e0d-431b-aed9-9a8b98b7d333)

**Comment by thelazyone** [comment]
Oh, I never tried to print the model directly "out of the box". The black areas are with inverted normals (which I will now fix), I would recommend to simply (according to google) "In Edit Mode, select the face that's incorrect, then go to “Mesh > Normals > Flip”"

Otherwise, remeshing always works well!

**Comment by ikaun** [comment]
Voxel Remesh looks great... here is what it looks like now

![image](https://github.com/thelazyone/lazy-tree/assets/61319817/bfb2579d-7ac2-4585-b4f9-be623c4f93c3)

**Comment by thelazyone** [comment]
I would recommend reducing the voxel size 2-3 times, just not to miss the curves of the bark! 
But other than that - it's a winner!

**Comment by ikaun** [comment]
Bad pic but first successful print! ... looks amazing... any tips on making trees that are more delicate and less trunk thickness... which settings should I play with? This is amazing! thank you

![image](https://github.com/thelazyone/lazy-tree/assets/61319817/71fbfac7-7bae-47ff-b19e-61091b5960ba)

**Comment by ikaun** [comment]
Another shot... this is a 28mm figure for size reference

![image](https://github.com/thelazyone/lazy-tree/assets/61319817/0747ab4f-2951-42b6-8e91-e8f974d3b12f)

**Comment by thelazyone** [comment]
That's really cool! 

A way to avoid the roots going too much forward is to print the model facing "up" on the printer, and with the roots below the "0" plane. 

Regarding the thick branches - play with the chunkyness parameter. It's very delicate, a 0.01 change does a lot. proceed by steps (possibly without the "generate mesh" tick on!

I'll try to fix the non-printable issue asap!

**Comment by ikaun** [comment]
Great idea! I kinda dig the roots though … it for a diorama so I’ll just bury em

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thelazyone** [comment]
Issue closed - The trees still require extra steps to be printable, but this is the current state of the art.
